[package]
name = "serve"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-files = "0.6.2"
actix-web = { version = "4.1.0", features = ["rustls"] }
rustls = "0.20.6"
rustls-pemfile = "1.0.0"

[[bin]]
name = "serve"
path = "./serve.rs"

[[bin]]
name = "servessl"
path = "./servessl.rs"
